- name: Create deployer/.ssh directory
  sudo: true
  sudo_user: deployer
  file:
    state=directory
    path=~/.ssh
    mode=700

- name: Setup SSH Authorized Keys
  sudo: true
  sudo_user: deployer
  template:
    src=authorized_keys
    dest=~/.ssh/authorized_keys
    mode=600

- name: Copy SSH Private Key
  sudo: true
  sudo_user: deployer
  template:
    src=id_rsa
    dest=~/.ssh/id_rsa
    mode=600

- name: Copy SSH Public Key
  sudo: true
  sudo_user: deployer
  template:
    src=id_rsa.pub
    dest=~/.ssh/id_rsa.pub
    mode=644

- name: Add Domain SSH Keys to known hosts
  sudo: true
  sudo_user: deployer
  shell: >
    ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
  with_items: "{{ deployer_ssh_keyscan_domains }}"
